<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class products_seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'product_name' => "Nike Dri-FIT Legend Men's Long-Sleeve Fitness Top",
                'product_price' => 1520000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Huyền thoại thấm mồ hôi trở lại với diện mạo và cảm nhận được cập nhật. Nó mềm mại theo mọi cách, với kiểu dáng thoải mái hơn, lỏng lẻo hơn so với các phiên bản trước để bạn có thể thực hiện các lần lặp lại của mình mà không bị lỡ nhịp.',
                'product_object_id' => 1,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike Pro Men's Dri-FIT Slim Long-Sleeve Fitness Top",
                'product_price' => 1762000,
                'rating' => 5,
                'purchasing_quantity' => 150,
                'quantity' => 30,
                'product_description' => 'Bộ sưu tập Nike Pro mang lại cảm giác tự tin trong bất kỳ giai đoạn nào của hành trình tập luyện mà bạn thấy mình. Chiếc áo thun dài tay dáng ôm này mang lại cảm giác mịn màng và co giãn cho các môn thể thao và hoạt động mà bạn yêu thích.',
                'product_object_id' => 1,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike DNA Men's Dri-FIT Basketball Jersey",
                'product_price' => 1490000,
                'rating' => 4,
                'purchasing_quantity' => 120,
                'quantity' => 40,
                'product_description' => 'Hãy sẵn sàng lên sàn vì bóng rổ không bao giờ dừng lại với chiếc áo Nike DNA. Mát mẻ, nhẹ và bền, thiết kế vừa vặn thoải mái được làm bằng lưới thoáng khí giúp bạn luôn mát mẻ trong khi cải thiện trò chơi của mình.',
                'product_object_id' => 1,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Jordan Sport Men's Graphic T-Shirt",
                'product_price' => 1689000,
                'rating' => 4,
                'purchasing_quantity' => 80,
                'quantity' => 20,
                'product_description' => 'Áo Jordan tươi mới trở nên sống động ở mặt trước và mặt sau của chiếc áo phông thoải mái này. Nó được cải tiến với công nghệ thấm mồ hôi, vì vậy bạn sẵn sàng chơi bóng hoặc biểu diễn nhào lộn quanh thị trấn—bạn sẽ trông như nghệ sĩ hạng A',
                'product_object_id' => 1,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Ja Standard Issue Men's Dri-FIT Pullover Basketball Hoodie",
                'product_price' => 1960000,
                'rating' => 5,
                'purchasing_quantity' => 90,
                'quantity' => 15,
                'product_description' => 'Ja Morant là một siêu sao tự thân lập nghiệp. Rời xa ánh đèn sân khấu, Ja lớn lên không mệt mỏi với trò chơi của mình trên sân sau nhà ở Nam Carolina. Từ vô danh trở thành ngôi sao toàn năng, Nike kỷ niệm hành trình của mình bằng bộ sưu tập trang phục đặc trưng này. Công nghệ Nike Dri-FIT di chuyển mồ hôi ra khỏi da để bay hơi nhanh hơn, giúp bạn khô ráo và thoải mái. Áo hoodie mềm Standard Issue của chúng tôi mang đến cảm giác vừa vặn thoải mái cùng với logo đặc trưng của Ja.',
                'product_object_id' => 1,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike Sportswear Classic Women's T-Shirt",
                'product_price' => 1300000,
                'rating' => 4,
                'purchasing_quantity' => 110,
                'quantity' => 25,
                'product_description' => 'Chất liệu cotton dày mang lại cho bạn cảm giác có cấu trúc và cao cấp, trong khi đường may hình hộp và đường may trễ vai tạo cảm giác thoải mái mà không có cảm giác quá rộng. Cổ điển và vượt thời gian—chiếc áo phông này làm được tất cả.',
                'product_object_id' => 2,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike Yoga Luxe Women's Infinalon Crop Top",
                'product_price' => 1459000,
                'rating' => 5,
                'purchasing_quantity' => 70,
                'quantity' => 10,
                'product_description' => 'Nike Yoga Luxe Crop Top được làm bằng vải Nike Infinalon cho cảm giác mềm mại, co giãn và mịn màng không thể cưỡng lại được đồng thời mang lại cảm giác nén nhẹ nhàng khi bạn thở, giãn cơ và di chuyển.',
                'product_object_id' => 2,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Jordan Flight Fleece Women's Crewneck Sweatshirt",
                'product_price' => 1290000,
                'rating' => 3,
                'purchasing_quantity' => 60,
                'quantity' => 30,
                'product_description' => 'Gặp gỡ chiếc áo len yêu thích mới của bạn. Cái mà bạn lôi ra khỏi đống quần áo bẩn vì quá tốt để không mặc thêm một lần nào nữa. (Sẽ không ai biết.) Siêu mềm với kiểu dáng hơi quá khổ và độ phồng ở tay áo, rất dễ mặc và hoàn hảo để mặc nhiều lớp.',
                'product_object_id' => 2,
                'product_type_id' => 1,
            ],
            [
                'product_name' => 'Nike Shine Long Sleeve Tee Little Kids T-Shirt',
                'product_price' => 1340000,
                'rating' => 5,
                'purchasing_quantity' => 80,
                'quantity' => 18,
                'product_description' => 'Những đứa trẻ sống theo bản năng "Cứ làm đi"; cuộc sống, và thông điệp được hiển thị ở mặt trước của chiếc áo phông vừa vặn thông thường này, được làm bằng vải dệt kim jersey mịn với đường viền cổ không có thẻ để mang lại cảm giác thoải mái, dễ mặc, tay áo dài có cổ tay có gân mang lại cảm giác ấm cúng và thiết kế đơn giản giúp bạn dễ dàng phối đồ. bất kỳ chiếc quần Nike nào hoặc chiếc quần jean yêu thích của họ để có vẻ ngoài vượt thời gian.',
                'product_object_id' => 3,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike Little Kids' Pullover Hoodie",
                'product_price' => 1280000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Áo hoodie Nike có tất cả những gì mà các bạn nhỏ mong muốn. Vải terry Pháp mềm mại với kiểu dáng rộng rãi, rộng rãi tạo cảm giác ấm cúng hơn.',
                'product_object_id' => 3,
                'product_type_id' => 1,
            ],
            [
                'product_name' => "Nike Sportswear Sport Essentials Men's Woven Lined Flow Shorts",
                'product_price' => 1960000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Cho dù bạn đang chạy đến xe bán đồ ăn gần nhất hay lao vào hố bơi yêu thích của mình, Quần short lót Nike Sportswear Sport Essentials là một ý tưởng hay. Được lót để tạo sự thoải mái, loại vải dệt mịn có trọng lượng nhẹ và thích hợp cho mọi cuộc phiêu lưu.',
                'product_object_id' => 1,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Flex Stride Men's 2-In-1 Running Shorts",
                'product_price' => 1620000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Quần short Nike Flex Stride được cập nhật bằng vải dệt hoàn toàn mới và tăng cường khả năng thoáng khí ở những vùng có nhiều mồ hôi. Lớp lót mềm của họ cung cấp sự hỗ trợ an toàn ở nơi bạn cần. Sản phẩm này được làm từ ít nhất 50% sợi polyester tái chế.',
                'product_object_id' => 1,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Jordan Dri-FIT Sport Men's Air Fleece Trousers",
                'product_price' => 1960000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Cho dù bạn đang chạy đến xe bán đồ ăn gần nhất hay lao vào hố bơi yêu thích của mình, Quần short lót Nike Sportswear Sport Essentials là một ý tưởng hay. Được lót để tạo sự thoải mái, loại vải dệt mịn có trọng lượng nhẹ và thích hợp cho mọi cuộc phiêu lưu.',
                'product_object_id' => 1,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Therma-FIT Men's Camo Tapered Training Pants",
                'product_price' => 1290000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Tận hưởng thời tiết mát mẻ với chiếc quần ống côn siêu mềm này. Chúng tôi đã bổ sung công nghệ điều chỉnh nhiệt để giúp bạn duy trì số lần tập, ngay cả khi trời lạnh. Chúng tôi cũng bổ sung thêm họa tiết rằn ri toàn thân lấy cảm hứng từ quân phục của quân đội Anh.',
                'product_object_id' => 1,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Universa Women's Medium-Support High-Waisted Full-Length Leggings with Pockets",
                'product_price' => 1960000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Cho dù bạn đang chạy đến xe bán đồ ăn gần nhất hay lao vào hố bơi yêu thích của mình, Quần short lót Nike Sportswear Sport Essentials là một ý tưởng hay. Được lót để tạo sự thoải mái, loại vải dệt mịn có trọng lượng nhẹ và thích hợp cho mọi cuộc phiêu lưu.',
                'product_object_id' => 2,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Yoga Dri-FIT Luxe Women's Flared Pants",
                'product_price' => 1290000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Hãy đơn giản nhưng không quá cơ bản với chiếc quần ống loe, cạp cao này. Vải Infinalon của họ mềm mại và mịn màng không thể cưỡng lại, đồng thời mang lại cảm giác nén nhẹ nhàng ôm lấy cơ thể bạn để bạn có thể co giãn và di chuyển không giới hạn. Với chất liệu vải thấm mồ hôi và dải thắt lưng rộng, bạn sẽ cảm thấy mát mẻ và được hỗ trợ khi chuyển từ tư thế này sang tư thế khác.',
                'product_object_id' => 2,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Sportswear Air Women's High-Waisted Flared Leggings",
                'product_price' => 1459000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Hãy ôm lấy eo cao rực rỡ trong mùa này. Dày nhưng vẫn nhẹ, mềm mại nhưng vẫn chắc chắn—chúng dễ dàng co giãn theo từng cử động của bạn.',
                'product_object_id' => 2,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Sportswear Club Fleece Big Kids' French Terry Shorts (Extended Size)",
                'product_price' => 1159000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => ' Lựa chọn lý tưởng khi cảm thấy quá ấm áp với chất liệu lông cừu chải kỹ, chiếc quần short này là lựa chọn hoàn hảo để chạy bộ trong thời tiết ấm áp. Vải terry mềm mại của Pháp mang lại cảm giác nhẹ nhàng—giống như những chiếc áo len cổ điển của bạn. Kéo chúng vào và thắt chặt bằng dây rút bên trong để vừa khít hoàn hảo mà bạn có thể tin cậy để tiếp tục di chuyển.',
                'product_object_id' => 3,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Trophy23 Big Kids' Dri-FIT Training Shorts",
                'product_price' => 1259000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Cho dù bạn đang mơ ước được chơi ở cấp độ tiếp theo hay là người mới bắt đầu học môn thể thao này, quần short Nike Trophy23 sẽ giúp bạn chuẩn bị sẵn sàng cho trận đấu. Chất liệu vải siêu thoáng khí giúp tản mồ hôi giúp bạn luôn mát mẻ và tự tin trong khi mài giũa kỹ năng của mình.',
                'product_object_id' => 3,
                'product_type_id' => 2,
            ],
            [
                'product_name' => "Nike Dri-FIT Academy23 Kids' Soccer Shorts",
                'product_price' => 1135000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => ' Bạn đã sẵn sàng ra sân chưa? Vải dệt kim mịn và mềm thấm mồ hôi giúp bạn luôn mát mẻ và thoải mái khi mang trò chơi hạng A của mình đến mọi giờ giải lao, luyện tập và vui chơi. Kiểu dáng vừa vặn cổ điển giúp bạn có không gian để di chuyển mà không bị phân tâm.',
                'product_object_id' => 3,
                'product_type_id' => 2,
            ],



            [
                'product_name' => "Nike Sportswear Club Fleece Big Kids' (Girls') Loose Pants",
                'product_price' => 1200000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Cho dù bạn đang đi tập thể dục, tập luyện nhóm hay đơn giản là leo núi với bạn bè, quần Nike Dri-FIT Multi+ Training Shorts giúp bạn làm điều đó thoải mái. Và mồ hôi? Với chất liệu nhẹ, thấm mồ hôi của chúng tôi, đó không phải là điều bạn cần phải lo lắng. Được thiết kế để giúp bạn giữ mát, chúng là sự lựa chọn cho tất cả mọi thứ vui vẻ.',
                'product_object_id' => 3,
                'product_type_id' => 2
            ],
            [
                'product_name' => "Nike Sportswear Club Fleece Big Kids' (Girls') Pants (Extended Size)",
                'product_price' => 1290000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Quần lông cừu Nike Sportswear Club còn rất thoải mái. Được làm bằng lông cừu siêu mềm, tất cả đều mang lại cảm giác ấm cúng, ấm áp. Với túi, cạp quần co giãn và cổ tay có gân, còn gì mà không thích?',
                'product_object_id' => 3,
                'product_type_id' => 2
            ],
            [
                'product_name' => "Jordan Stadium 90 Men's Shoes",
                'product_price' => 3200000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Sự thoải mái là vua, nhưng điều đó không có nghĩa là bạn phải hy sinh phong cách. Lấy cảm hứng thiết kế từ AJ1 và AJ5, Stadium 90 sẵn sàng để đeo hàng ngày. Phần trên được làm bằng da tổng hợp và vải dệt, thể hiện sự kết hợp giữa hộp ngón chân AJ1 và các chi tiết ngọn lửa từ AJ5. Đệm Nike Air giúp mỗi bước đi trở nên dễ dàng như phong cách của bạn.',
                'product_object_id' => 1,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike Dunk Mid Men's Shoes",
                'product_price' => 3500000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Được tạo ra dành cho gỗ cứng nhưng lại được ưa chuộng trên đường phố, biểu tượng b-ball của thập niên 80 trở lại với chất liệu da sắc nét và kiểu dáng cổ điển "Panda" chặn màu. Thiết kế vòng cổ điển mang hơi hướng cổ điển của thập niên 80 trở lại đường phố trong khi cổ áo có đệm ở giữa trên tạo thêm vẻ cổ điển tạo cảm giác thoải mái.',
                'product_object_id' => 1,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike Air Force 1 '07 Men's Shoes",
                'product_price' => 2900000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Thoải mái, bền bỉ và vượt thời gian—không có lý do gì nó là số 1. Cấu trúc của thập niên 80 kết hợp với màu sắc cổ điển để tạo nên phong cách phù hợp dù bạn đang ở trên sân hay đang di chuyển.',
                'product_object_id' => 1,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike MC Trainer 2 Men’s Workout Shoes",
                'product_price' => 3050000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Kết thúc lần tập cuối cùng của bạn một cách mạnh mẽ và thực hiện nó bằng một tiếng gầm làm choáng váng sàn phòng tập với Nike Air Max Alpha Trainer 5. Đệm Max Air mang lại sự ổn định thoải mái khi nâng dù đó là ngày nhẹ hay nặng. Đế phẳng, rộng giúp bạn nâng cao độ ổn định và độ bám cho mọi loại bài tập khó mà không ảnh hưởng đến phong cách khi bạn di chuyển từ trạm này sang trạm khác và bắt đầu cài đặt.',
                'product_object_id' => 1,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike Air Max Alpha Trainer 5 Men's Workout Shoes",
                'product_price' => 3240000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Kết thúc lần tập cuối cùng của bạn một cách mạnh mẽ và thực hiện nó bằng một tiếng gầm làm choáng váng sàn phòng tập với Nike Air Max Alpha Trainer 5. Đệm Max Air mang lại sự ổn định thoải mái khi nâng dù đó là ngày nhẹ hay nặng. Đế phẳng, rộng giúp bạn nâng cao độ ổn định và độ bám cho mọi loại bài tập khó mà không ảnh hưởng đến phong cách khi bạn di chuyển từ trạm này sang trạm khác và bắt đầu cài đặt.',
                'product_object_id' => 1,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Air Jordan 1 Brooklyn Women's Boots",
                'product_price' => 3930000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Đôi giày sneaker táo bạo, chắc chắn này chính là chìa khóa cho sự xoay chuyển của bạn. Da nguyên hạt sang trọng kết hợp với đế đế dày để nâng cao phong cách cá nhân của bạn. Các vấu đế ngoài phóng đại và đệm Nike Air hỗ trợ các bước của bạn. Và đừng ngủ quên trên AJ1 DNA: một viên kim cương ở gót chân hiển thị phù hiệu Jumpman, tạo điểm nhấn cho vẻ ngoài của bạn về di sản của môn thể thao vòng.',
                'product_object_id' => 2,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Jordan Nu Retro 1 Low Men's Shoes",
                'product_price' => 2950000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Lấy cảm hứng từ logo và thiết kế Wings nguyên bản của Jordan 1, những đôi giày hàng ngày này luôn sẵn sàng cho mọi hoạt động. Hãy diện chúng với một vài chiếc quần jean rộng thùng thình, trượt băng trong bộ quần áo đó hoặc chỉ đơn giản là trông bay bổng—điều đó tùy thuộc vào bạn. Mũ giày bằng da mịn và logo in nổi lớn sẽ giúp bạn nổi bật dù mặc trang phục sang trọng hay giản dị.',
                'product_object_id' => 2,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Air Jordan 1 Low SE Craft Men's Shoes",
                'product_price' => 2850000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Màu sắc mới và kết cấu mới mẻ mang đến cho bạn một chiếc AJ1 thủ công, giữ được vẻ cổ điển và cảm giác quen thuộc. Chiếc áo được yêu thích nhất mọi thời đại này được làm bằng vật liệu cao cấp và được trang trí bằng các cạnh thô và đường khâu tương phản.',
                'product_object_id' => 2,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike Vaporfly 3 Women's Road Racing Shoes",
                'product_price' => 3120000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Mang đến cho bạn tốc độ trong ngày đua để chinh phục mọi khoảng cách, Vaporfly 3 dành cho những người theo đuổi, những tay đua và những người có tốc độ cao, những người không thể từ chối cảm giác hồi hộp khi theo đuổi. Chúng tôi đã làm lại phần dẫn đầu của gói giày siêu hạng và điều chỉnh động cơ bên dưới để giúp bạn theo đuổi thành tích cá nhân từ cự ly 10 km đến chạy marathon.',
                'product_object_id' => 2,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Nike Kiger 9 Women's Trail Running Shoes",
                'product_price' => 250000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Khi tiếp cận các địa hình nhiều đá và kỹ thuật, hãy di chuyển với sự thoải mái và tốc độ của Kiger 9, sẵn sàng đối phó với mọi khúc cua và khúc cua gấp bất ngờ. Được trang bị bọt Nike React có chiều dài đầy đủ và phần trên thoáng khí được tân trang lại, đôi giày tập nhanh nhẹn, linh hoạt này giúp bạn chạy ngoằn ngoèo trong và ngoài đường mòn với tốc độ nhanh. Nó thấp hơn mặt đất và nhẹ hơn so với phiên bản trước của chúng tôi, để bạn có thể xử lý đường địa hình một cách nhanh chóng và an toàn.',
                'product_object_id' => 2,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Ja 1 \"Backyard BBQ\" Big Kids' Basketball Shoes",
                'product_price' => 2350000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Mang đến cho bạn tốc độ trong ngày đua để chinh phục mọi khoảng cách, Vaporfly 3 dành cho những người theo đuổi, những tay đua và những người có tốc độ cao, những người không thể từ chối cảm giác hồi hộp khi theo đuổi. Chúng tôi đã làm lại phần dẫn đầu của gói giày siêu hạng và điều chỉnh động cơ bên dưới để giúp bạn theo đuổi thành tích cá nhân từ cự ly 10 km đến chạy marathon.',
                'product_object_id' => 3,
                'product_type_id' => 3
            ],
            [
                'product_name' => "Tatum 1 Little Kids' Shoes",
                'product_price' => 2430000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Tatum 1 được thiết kế để dễ dàng mang vào, vì vậy trẻ em có thể tự mang giày và bắt đầu giờ chơi nhanh hơn. Chỉ cần yêu cầu họ BƯỚC theo đúng yêu cầu và sự đổi mới về quyền trẻ em sẽ giúp họ phù hợp. Nhẹ, bền và an toàn, chúng có đôi chân nhỏ được bảo vệ trong mỗi bước đi lớn.',
                'product_object_id' => 3,
                'product_type_id' => 3
            ],
            [
                'product_name' => "LeBron Witness 7 Little Kids' Shoes",
                'product_price' => 2450000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 22,
                'product_description' => 'Từ sân chơi đến lớp thể dục, LeBron Witness 7 mang đến cho con bạn cảm giác MVP. Thiết kế nhẹ và thoáng khí giúp chân luôn mát mẻ khi chạy xung quanh. Và, chúng tôi làm mọi thứ trở nên cực kỳ đơn giản với dây thun chéo và dây đeo, để siêu sao tương lai của bạn có thể cảm thấy tự tin vui vẻ khi mặc lại mọi thứ LeBron.',
                'product_object_id' => 3,
                'product_type_id' => 3
            ],






            [
                'product_name' => "LeBron Witness 7 Big Kids' Basketball Shoes",
                'product_price' => 3550000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Từ sân chơi đến lớp thể dục, LeBron Witness 7 mang đến cho đôi chân của bạn cảm giác MVP với thiết kế nhẹ và thoáng khí nhưng vẫn mang lại nhiều sự hỗ trợ. Đệm Max Air có chiều dài tối đa giúp bạn cất cánh và hạ cánh một cách tự tin, trong khi lưới và dây cáp nhẹ giúp bạn luôn cố định trong 4/4—hoặc hơn.',
                'product_object_id' => 3,
                'product_type_id' => 3,
            ],
            [
                'product_name' => "Nike Everyday Plus Cushioned Training Crew Socks (6 Pairs)",
                'product_price' => 560000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Từ sân chơi đến lớp thể dục, LeBron Witness 7 mang đến cho đôi chân của bạn cảm giác MVP với thiết kế nhẹ và thoáng khí nhưng vẫn mang lại nhiều sự hỗ trợ. Đệm Max Air có chiều dài tối đa giúp bạn cất cánh và hạ cánh một cách tự tin, trong khi lưới và dây cáp nhẹ giúp bạn luôn cố định trong 4/4—hoặc hơn.',
                'product_object_id' => 1,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Plus Cushioned Training Crew Socks (3 Pairs)",
                'product_price' => 512000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Vượt qua giới hạn của bạn với Tất có đệm Nike Everyday Max. Đế terry dày giúp bạn thoải mái hơn khi tập và nâng chân trong khi sợi có độ ma sát cao ở lòng bàn chân giúp giảm trượt',
                'product_object_id' => 1,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Elite Crew Basketball Socks",
                'product_price' => 625000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Tất bóng rổ Nike Elite Crew mang lại cảm giác vừa vặn và hỗ trợ nhờ dải vòm, trong khi lớp đệm theo vùng giúp hấp thụ tác động khi bạn chạy trên sân.',
                'product_object_id' => 1,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Multiplier Crew Sock (2 Pairs)",
                'product_price' => 69300,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Nhảy cao với chiếc tất Nike Multiplier Crew (2 đôi). Vải thấm mồ hôi giúp bạn luôn khô ráo và mát mẻ, trong khi lưới dọc theo phần giữa bàn chân giúp bạn thoáng khí. Một "NIKE" tuyến tính logo nổi bật khi bạn chạy.',
                'product_object_id' => 1,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Lightweight Training No-Show Socks (6 Pairs)",
                'product_price' => 415000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Hãy mua một đôi tất phù hợp với tâm trạng của bạn. Nếu một ngày tươi sáng và tràn đầy năng lượng đưa bạn vào một cuộc phiêu lưu mới—hoặc có thể chỉ là một chuyến đi dạo bình thường quanh khu nhà—bạn sẽ được chuẩn bị sẵn công nghệ thấm mồ hôi giúp bạn luôn mát mẻ và khô ráo, cùng với một dải băng ôm quanh vòm để được hỗ trợ thêm.',
                'product_object_id' => 2,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Lightweight Training No-Show Socks (3 Pairs)",
                'product_price' => 269000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Tăng cường sức mạnh cho quá trình tập luyện của bạn với Tất nhẹ hàng ngày của Nike. Sợi mềm với công nghệ thấm mồ hôi giúp đôi chân bạn luôn thoải mái và khô ráo.',
                'product_object_id' => 2,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Plus Cushioned Crew Socks (2 Pairs)",
                'product_price' => 268000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Giờ đây, bạn có thể mang linh vật hộp giày yêu quý này đi bất cứ nơi đâu trong chuyến phiêu lưu tiếp theo của bạn. Và trong khi Boxy ở đây để mang đi, bạn cũng ở đây để có vòm có dải hỗ trợ và công nghệ thấm mồ hôi giúp bạn khô ráo suốt cả ngày.',
                'product_object_id' => 2,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Jordan Everyday Ankle Socks (3 Pairs)",
                'product_price' => 569000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Những đôi tất đến mắt cá chân này sẽ giúp bạn luôn khô ráo và mát mẻ với chất liệu vải thấm mồ hôi và tấm lót mắt cá chân thoáng khí. Chúng vừa khít quanh vòm để mang lại cho bạn cảm giác được hỗ trợ nhiều hơn.',
                'product_object_id' => 2,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Lightweight Training No-Show Socks (3 Pairs)",
                'product_price' => 560000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Tăng cường sức mạnh cho quá trình tập luyện của bạn với Tất nhẹ hàng ngày của Nike. Sợi mềm với công nghệ thấm mồ hôi giúp đôi chân bạn luôn thoải mái và khô ráo.',
                'product_object_id' => 3,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Nike Everyday Plus Cushioned Crew Socks (2 Pairs)",
                'product_price' => 340000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Giờ đây, bạn có thể mang linh vật hộp giày yêu quý này đi bất cứ nơi đâu trong chuyến phiêu lưu tiếp theo của bạn. Và trong khi Boxy ở đây để mang đi, bạn cũng ở đây để có vòm có dải hỗ trợ và công nghệ thấm mồ hôi giúp bạn khô ráo suốt cả ngày.',
                'product_object_id' => 3,
                'product_type_id' => 4,
            ],
            [
                'product_name' => "Jordan Everyday Ankle Socks (3 Pairs)",
                'product_price' => 440000,
                'rating' => 4,
                'purchasing_quantity' => 100,
                'quantity' => 50,
                'product_description' => 'Những đôi tất đến mắt cá chân này sẽ giúp bạn luôn khô ráo và mát mẻ với chất liệu vải thấm mồ hôi và tấm lót mắt cá chân thoáng khí. Chúng vừa khít quanh vòm để mang lại cho bạn cảm giác được hỗ trợ nhiều hơn.',
                'product_object_id' => 3,
                'product_type_id' => 4,
            ],
        ]);
    }
}
